apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: golang-redis
  namespace: redis
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: golang-redis
  targetCPUUtilizationPercentage: 70
  behavior:
    scaleDown:
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Min