apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: golang-redis
  namespace: redis
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: v1
    kind: Deployment
    name: golang-redis
  targetCPUUtilizationPercentage: 1