name: Docker Image CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
         name: Checkout
         uses: actions/checkout@v2
      - 
         name: Login to Docker Hub
         uses: docker/login-action@v1
         with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_TOKEN }}
      -
         name: docker build
         run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_IMAGE }}
      -
         name: Docker push
         run: docker push ${{ secrets.DOCKER_IMAGE }}
      -   
         name: 'Noti JOM'
         uses: snow-actions/line-notify@v1.0.0
         with:
             access_token: ${{ secrets.LINE_TOKEN }}
             message: ${{ secrets.DOCKER_IMAGE }} PUSH to dockerhub complete.!!!
